[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.circleci
  | venv_flask
  | _build
  | buck-out
  | build
  | dist
  | frontend
  | _docs
)/
'''
